import { IMenu } from "./menu.js";

export const DEFAULTDOCUMENT = "docs/gettingstarted/home";
export const CURRENTVERSION = "0.3.8";

export const THEMEDB = [
	{
		value: "light",
		icon: { id: "sun-fill" },
		label: "Light",
	},
	{
		value: "dark",
		icon: { id: "moon-stars-fill" },
		label: "Dark",
	},
	{
		value: "auto",
		icon: { id: "circle-half" },
		label: "Auto",
	},
];

export const BOOTSWATCHDB = [
	{
		value: "default",
		label: "Default",
	},
	{ value: "cerulean", label: "Cerulean" },
	{ value: "cosmo", label: "Cosmo" },
	{ value: "cyborg", label: "Cyborg" },
	{ value: "darkly", label: "Darkly" },
	{ value: "flatly", label: "Flatly" },
	{ value: "journal", label: "Journal" },
	{ value: "litera", label: "Litera" },
	{ value: "lumen", label: "Lumen" },
	{ value: "lux", label: "Lux" },
	{ value: "materia", label: "Materia" },
	{ value: "minty", label: "Minty" },
	{ value: "morph", label: "Morph" },
	{ value: "pulse", label: "Pulse" },
	{ value: "quartz", label: "Quartz" },
	{ value: "sandstone", label: "Sandstone" },
	{ value: "simplex", label: "Simplex" },
	{ value: "sketchy", label: "Sketchy" },
	{ value: "slate", label: "Slate" },
	{ value: "solar", label: "Solar" },
	{ value: "spacelab", label: "Spacelab" },
	{ value: "superhero", label: "Superhero" },
	{ value: "united", label: "United" },
	{ value: "vapor", label: "Vapor" },
	{ value: "yeti", label: "Yeti" },
	{ value: "zephyr", label: "Zephyr" },
];

export const COLORPALLETDB = (): {
	light: string;
	dark: string;
	primary: string;
	secondary: string;
	info: string;
	success: string;
	warning: string;
	danger: string;
}[] => {
	return [
		{
			light: "#f8f9fa",
			dark: "#212529",
			primary: "#0d6efd",
			secondary: "#6c757d",
			info: "#0dcaf0",
			success: "#198754",
			warning: "#ffc107",
			danger: "#dc3545",
		},
		{
			light: "#add4cd",
			dark: "#290405",
			primary: "#610ebb",
			secondary: "#e85129",
			info: "#e5a832",
			success: "#0cad69",
			warning: "#e2ce0b",
			danger: "#f22704",
		},
		{
			light: "#c1f0fa",
			dark: "#0b0d0e",
			primary: "#731949",
			secondary: "#e62c74",
			info: "#dcb0a9",
			success: "#1fa976",
			warning: "#d6d11e",
			danger: "#e2410e",
		},
		{
			light: "#f9e6c1",
			dark: "#2b170b",
			primary: "#0d4a3c",
			secondary: "#42878a",
			info: "#00e0e2",
			success: "#00b03b",
			warning: "#f5c800",
			danger: "#f8003f",
		},
		{
			light: "#d9f8fe",
			dark: "#00263c",
			primary: "#043150",
			secondary: "#ea1570",
			info: "#f4d1c6",
			success: "#0cac60",
			warning: "#e7cc0b",
			danger: "#f80804",
		},
		{
			light: "#f5c8c3",
			dark: "#070706",
			primary: "#c4a04d",
			secondary: "#504e3e",
			info: "#be5c56",
			success: "#51a629",
			warning: "#fdc151",
			danger: "#f0175d",
		},
		{
			light: "#e0e6f2",
			dark: "#20095d",
			primary: "#3300f5",
			secondary: "#c8787b",
			info: "#fad9cf",
			success: "#00ba6e",
			warning: "#e7d100",
			danger: "#fa2100",
		},
		{
			light: "#cfd2f2",
			dark: "#040f28",
			primary: "#63c3d2",
			secondary: "#136364",
			info: "#a85b89",
			success: "#14af55",
			warning: "#edcb13",
			danger: "#f8082c",
		},
		{
			light: "#d1efee",
			dark: "#040530",
			primary: "#3840b4",
			secondary: "#d83e88",
			info: "#ebba9f",
			success: "#2daf6c",
			warning: "#e4cf2b",
			danger: "#f32817",
		},
		{
			light: "#f1e5aa",
			dark: "#0a0807",
			primary: "#5f3527",
			secondary: "#954527",
			info: "#d50031",
			success: "#4e9400",
			warning: "#ffba43",
			danger: "#ea0060",
		},
		{
			light: "#e4d8d1",
			dark: "#191728",
			primary: "#483b2a",
			secondary: "#e7342e",
			info: "#f94134",
			success: "#4a9d13",
			warning: "#febd37",
			danger: "#ed095c",
		},
		{
			light: "#ccf1eb",
			dark: "#070c0d",
			primary: "#0f3943",
			secondary: "#c62c44",
			info: "#5944e8",
			success: "#19974e",
			warning: "#e4c51c",
			danger: "#ed0d25",
		},
		{
			light: "#bcd2ee",
			dark: "#0e060b",
			primary: "#003bfc",
			secondary: "#56443c",
			info: "#e14355",
			success: "#009858",
			warning: "#dec800",
			danger: "#eb1c00",
		},
		{
			light: "#cde8dd",
			dark: "#2f155a",
			primary: "#3e4349",
			secondary: "#3266f8",
			info: "#0078b0",
			success: "#009a53",
			warning: "#e2c700",
			danger: "#f00005",
		},
		{
			light: "#c8e9f9",
			dark: "#230749",
			primary: "#002ca1",
			secondary: "#9c3097",
			info: "#c1a5bf",
			success: "#00a05d",
			warning: "#e0ca00",
			danger: "#ef1b00",
		},
		{
			light: "#b5b5a7",
			dark: "#6e3a3b",
			primary: "#6f5560",
			secondary: "#866868",
			info: "#c4faf5",
			success: "#3cb784",
			warning: "#dad535",
			danger: "#e6471d",
		},
		{
			light: "#8f5e52",
			dark: "#05283c",
			primary: "#c9254e",
			secondary: "#e96796",
			info: "#97f286",
			success: "#72bc24",
			warning: "#fec88b",
			danger: "#fb126d",
		},
		{
			light: "#ede9fb",
			dark: "#462eac",
			primary: "#0f60ff",
			secondary: "#c860f7",
			info: "#debefc",
			success: "#00be6e",
			warning: "#ead200",
			danger: "#fd1c00",
		},
		{
			light: "#a9e5fb",
			dark: "#353476",
			primary: "#a185d5",
			secondary: "#969ce8",
			info: "#debefc",
			success: "#19ca7d",
			warning: "#ead613",
			danger: "#fe2c08",
		},
		{
			light: "#cde8dd",
			dark: "#2f155a",
			primary: "#3e4349",
			secondary: "#3266f8",
			info: "#0078b0",
			success: "#009a53",
			warning: "#e2c700",
			danger: "#f00005",
		},
		{
			light: "#dadef2",
			dark: "#1a1a29",
			primary: "#493085",
			secondary: "#d84357",
			info: "#7b5ec3",
			success: "#2d9861",
			warning: "#dcc930",
			danger: "#e62c1a",
		},
		{
			light: "#0c40d5",
			dark: "#f5f100",
			primary: "#074712",
			secondary: "#129458",
			info: "#f92a0c",
			success: "#05a113",
			warning: "#f5c206",
			danger: "#f00248",
		},
		{
			light: "#c8e9f9",
			dark: "#230749",
			primary: "#002ca1",
			secondary: "#9c3097",
			info: "#c1a5bf",
			success: "#00a05d",
			warning: "#e0ca00",
			danger: "#ef1b00",
		},
		{
			light: "#dce3e1",
			dark: "#130025",
			primary: "#91154b",
			secondary: "#d10f78",
			info: "#ecad47",
			success: "#0ba976",
			warning: "#d4d20a",
			danger: "#e14203",
		},
		{
			light: "#ffedd2",
			dark: "#080403",
			primary: "#643e2d",
			secondary: "#dc5540",
			info: "#eeb370",
			success: "#61aa2e",
			warning: "#fdc26f",
			danger: "#f11a65",
		},
	];
};

export const menuFS = [
	{ label: "Album", value: "docs/example/album" },
	{ label: "Pricing", value: "docs/example/pricing" },
	{ label: "Checkout", value: "docs/example/checkout" },
	{ label: "Product", value: "docs/example/product" },
];

export const menu: IMenu[] = [
	{
		label: "Getting started",
		icon: { id: "book-half", textColor: "primary" },
		item: [
			{ label: "Introduction", value: "docs/gettingstarted/introduction" },
			{ label: "Bootswatch", value: "docs/gettingstarted/bootswatch" },
		],
	},
	{
		label: "Customize",
		icon: { id: "palette2", textColor: "danger" },
		item: [{ label: "Color", value: "docs/customize/color" }],
	},
	{
		label: "Layout",
		icon: { id: "grid-fill", textColor: "success" },
		item: [
			{ label: "Breakpoints", value: "docs/layout/breakpoints" },
			{ label: "Containers", value: "docs/layout/containers" },
			{ label: "Grid", value: "docs/layout/grid" },
			{ label: "Columns", value: "docs/layout/columns" },
			{ label: "Gutters", value: "docs/layout/gutters" },
			{ label: "Utilities", value: "docs/layout/utilities" },
			{ label: "Z-index", value: "docs/layout/zindex" },
			{ label: "CSS Grid", value: "docs/layout/cssgrid" },
		],
	},
	{
		label: "Content",
		icon: { id: "file-earmark-richtext", textColor: "secondary" },
		item: [
			{ label: "Reboot", value: "docs/content/reboot" },
			{ label: "Typography", value: "docs/content/typography" },
			{ label: "Images", value: "docs/content/images" },
			{ label: "Tables", value: "docs/content/tables" },
			{ label: "Figures", value: "docs/content/figures" },
		],
	},
	{
		label: "Forms",
		icon: { id: "ui-radios", textColor: "primary" },
		item: [
			{ label: "Overview", value: "docs/forms/overview" },
			{ label: "Form control", value: "docs/forms/control" },
			{ label: "Select", value: "docs/forms/select" },
			{ label: "Checks & radios", value: "docs/forms/check_radio" },
			{ label: "Range", value: "docs/forms/range" },
			{ label: "Input group", value: "docs/forms/input_group" },
			{ label: "Floating labels", value: "docs/forms/floating_label" },
			{ label: "Layout", value: "docs/forms/layout" },
			{ label: "Validation", value: "docs/forms/validation" },
		],
	},
	{
		label: "Component",
		icon: { id: "menu-button-wide-fill", textColor: "info" },
		item: [
			{ label: "Accordion", value: "docs/components/accordion" },
			{ label: "Alert", value: "docs/components/alert" },
			{ label: "Badge", value: "docs/components/badge" },
			{ label: "Breadcrumb", value: "docs/components/breadcrumb" },
			{ label: "Button", value: "docs/components/button" },
			{ label: "Button group", value: "docs/components/button_group" },
			{ label: "Card", value: "docs/components/card" },
			{ label: "Carousel", value: "docs/components/carousel" },
			{ label: "Close button", value: "docs/components/close_button" },
			{ label: "Collapse", value: "docs/components/collapse" },
			{ label: "Dropdowns", value: "docs/components/dropdown" },
			{ label: "List group", value: "docs/components/list" },
			{ label: "Modal", value: "docs/components/modal" },
			{ label: "Navbar", value: "docs/components/navbar" },
			{ label: "Navs & tabs", value: "docs/components/nav" },
			{ label: "Offcanvas", value: "docs/components/offcanvas" },
			{ label: "Pagination", value: "docs/components/pagination" },
			{ label: "Placeholder", value: "docs/components/placeholder" },
			{ label: "Popovers", value: "docs/components/popover" },
			{ label: "Progress", value: "docs/components/progress" },
			{ label: "Scrollspy", value: "docs/components/scrollspy" },
			{ label: "Spinners", value: "docs/components/spinner" },
			{ label: "Toasts", value: "docs/components/toast" },
			{ label: "Tooltips", value: "docs/components/tooltip" },
		],
	},
	{
		label: "Helpers",
		icon: { id: "magic", textColor: "warning" },
		item: [
			{ label: "Clearfix", value: "docs/helpers/clearfix" },
			{ label: "Color & background", value: "docs/helpers/color_background" },
			{ label: "Colored links", value: "docs/helpers/colored_links" },
			{ label: "Focus ring", value: "docs/helpers/focus_ring" },
			{ label: "Icon link", value: "docs/helpers/icon_link" },
			{ label: "Position", value: "docs/helpers/position" },
			{ label: "Ratio", value: "docs/helpers/ratio" },
			{ label: "Stacks", value: "docs/helpers/stacks" },
			{ label: "Stretched link", value: "docs/helpers/stretched_link" },
			{ label: "Text truncation", value: "docs/helpers/text_truncation" },
			{ label: "Vertical rule", value: "docs/helpers/vertical_rule" },
			{ label: "Visually hidden", value: "docs/helpers/visually_hidden" },
		],
	},
	{
		label: "Utilities",
		icon: { id: "braces-asterisk", textColor: "danger" },
		item: [
			{ label: "API", value: "docs/utilities/api" },
			{ label: "Background", value: "docs/utilities/background" },
			{ label: "Borders", value: "docs/utilities/borders" },
			{ label: "Colors", value: "docs/utilities/colors" },
			{ label: "Display", value: "docs/utilities/display" },
			{ label: "Flex", value: "docs/utilities/flex" },
			{ label: "Float", value: "docs/utilities/float" },
			{ label: "Interactions", value: "docs/utilities/interactions" },
			{ label: "Link", value: "docs/utilities/link" },
			{ label: "Object fit", value: "docs/utilities/object_fit" },
			{ label: "Opacity", value: "docs/utilities/opacity" },
			{ label: "Overflow", value: "docs/utilities/overflow" },
			{ label: "Position", value: "docs/utilities/position" },
			{ label: "Shadows", value: "docs/utilities/shadow" },
			{ label: "Sizing", value: "docs/utilities/sizing" },
			{ label: "Spacing", value: "docs/utilities/spacing" },
			{ label: "Text", value: "docs/utilities/text" },
			{ label: "Vertical align", value: "docs/utilities/vertical_align" },
			{ label: "Visibility", value: "docs/utilities/visibility" },
			{ label: "Z-index", value: "docs/utilities/zindex" },
		],
	},
	{
		label: "Snippets",
		icon: { id: "code", textColor: "success" },
		item: [
			{ label: "Headers", value: "docs/snippets/headers" },
			{ label: "Heroes", value: "docs/snippets/heroes" },
			{ label: "Features", value: "docs/snippets/features" },
			{ label: "Sidebars", value: "docs/snippets/sidebars" },
			{ label: "Footers", value: "docs/snippets/footers" },
			{ label: "Dropdowns", value: "docs/snippets/dropdowns" },
			{ label: "List groups", value: "docs/snippets/list_groups" },
			{ label: "Modals", value: "docs/snippets/modals" },
			{ label: "Badges", value: "docs/snippets/badges" },
			{ label: "Breadcrumbs", value: "docs/snippets/breadcrumbs" },
			{ label: "Buttons", value: "docs/snippets/buttons" },
			{ label: "Jumbotrons", value: "docs/snippets/jumbotrons" },
		],
	},
	{
		label: "Example",
		icon: { id: "archive-fill", textColor: "secondary" },
		item: menuFS,
	},
	{
		label: "More",
		icon: { id: "hexagon-fill", textColor: "primary" },
		item: [
			{ label: "Animation", value: "docs/bsts/animation" },
			{ label: "Transform", value: "docs/bsts/transform" },
			{ label: "Extended property", value: "docs/bsts/extended_prop" },
			{ label: "Chart", value: "docs/bsts/chart" },
			{ label: "Test", value: "docs/bsts/test" },
		],
	},
];
