import {
	container,
	genMainContent,
	IAttrBSMainContainer,
	IAttrContent,
	IAttrFooter,
	IAttrFooterItem,
	IAttrItemInsideLink,
	IAttrItemMenu,
	IAttrItemOutsideLink,
	IAttrItemSubMenu,
	IAttrItemTheme,
	IAttrItemVersion,
	IAttrTocItem,
} from "./container";

export {
	container,
	genMainContent,
	IAttrBSMainContainer,
	IAttrContent,
	IAttrFooter,
	IAttrFooterItem,
	IAttrItemInsideLink,
	IAttrItemMenu,
	IAttrItemOutsideLink,
	IAttrItemSubMenu,
	IAttrItemTheme,
	IAttrItemVersion,
	IAttrTocItem,
};
